-- =============================================================================
-- ACTIVITY COACH — SUPABASE SCHEMA
-- Last updated: May 2026
-- =============================================================================
-- This file is the source of truth for the database structure.
-- If rebuilding from scratch, run this entire file in the Supabase SQL editor.
-- =============================================================================


-- =============================================================================
-- TABLE: activities
-- Stores every activity logged — manual entry or extracted from screenshot
-- =============================================================================
create table activities (
  id uuid default gen_random_uuid() primary key,

  -- Activity type — includes static options plus 'other' for free text
  type text not null check (type in (
    'running',
    'cycling_indoor',
    'cycling_outdoor',
    'fishing',
    'kung_fu',
    'gym',
    'other'
  )),

  -- When the activity took place
  date timestamptz not null default now(),

  -- Duration in minutes
  duration_minutes integer not null check (duration_minutes > 0),

  -- Optional fields
  notes text,
  distance_km numeric(6, 2),

  -- When the row was created
  created_at timestamptz default now()

  column avg_heart_rate integer,
 column avg_pace text,
 column avg_speed_kmh numeric(5,1),
 column elevation_m integer,
 column calories integer,
 column avg_power_w integer,
 column ai_notes text;
);

alter table activities enable row level security;
create policy "Allow all on activities" on activities for all using (true) with check (true);


-- =============================================================================
-- TABLE: mood_logs
-- Daily mood and energy check-ins (1-5 scale)
-- Used by the agent to contextualise suggestions
-- =============================================================================
create table mood_logs (
  id uuid default gen_random_uuid() primary key,

  -- The date this log is for
  log_date date not null default current_date,

  -- 1 (bad) to 5 (great)
  mood_score integer not null check (mood_score between 1 and 5),

  -- 1 (exhausted) to 5 (energised)
  energy_score integer not null check (energy_score between 1 and 5),

  -- Optional context for the agent
  notes text,

  created_at timestamptz default now(),

  -- One entry per day maximum
  unique(log_date)
);

alter table mood_logs enable row level security;
create policy "Allow all on mood_logs" on mood_logs for all using (true) with check (true);


-- =============================================================================
-- TABLE: agent_suggestions
-- Stores every suggestion generated by the Claude agent
-- Used to avoid repetition and track suggestion history
-- =============================================================================
create table agent_suggestions (
  id uuid default gen_random_uuid() primary key,

  -- The date this suggestion was generated for
  suggestion_date date not null default current_date,

  -- Which activity was suggested
  suggested_activity text not null,

  -- Full suggestion text from Claude
  suggestion_text text not null,

  -- Claude's internal reasoning (stored separately for debugging)
  reasoning text,

  -- Whether the user followed the suggestion (for future feedback loops)
  was_followed boolean,

  -- Whether the daily email was sent successfully
  email_sent boolean default false,

  created_at timestamptz default now(),

  kung_fu_element text,
kung_fu_suggestion text,

  -- One suggestion per day
  unique(suggestion_date)
);

alter table agent_suggestions enable row level security;
create policy "Allow all on agent_suggestions" on agent_suggestions for all using (true) with check (true);


-- =============================================================================
-- TABLE: diet_logs
-- Daily diet and weight logging
-- Nutritional data extracted from Nutra Check screenshots via Claude vision
-- Weight logged manually via popup on app open
-- =============================================================================
create table diet_logs (
  id uuid default gen_random_uuid() primary key,

  -- The date the food was consumed (extracted from screenshot)
  -- Not necessarily yesterday — could be any date within 7 days
  log_date date not null,

  -- When the user actually uploaded/created this entry
  created_at timestamptz default now(),

  -- Weight in kg (logged separately from diet, can exist independently)
  weight_kg numeric(5, 2),

  -- Nutritional data from Nutra Check
  kcal integer,
  fat_g numeric(6, 1),
  sat_fat_g numeric(6, 1),
  carbs_g numeric(6, 1),
  sugar_g numeric(6, 1),
  fibre_g numeric(6, 1),
  protein_g numeric(6, 1),
  salt_g numeric(6, 2),

  -- Percentage of daily guide (used by agent for context)
  kcal_pct integer,
  protein_pct integer,

  -- One entry per day
  unique(log_date)
);

alter table diet_logs enable row level security;
create policy "Allow all on diet_logs" on diet_logs for all using (true) with check (true);
-- =============================================================================
-- TABLE: settings
-- Generic key/value store for app settings
-- Currently used for: goal
-- Can be extended for future settings without new tables
-- =============================================================================
create table settings (
  id uuid default gen_random_uuid() primary key,

  -- Setting name e.g. 'goal'
  key text not null unique,

  -- Setting value — free text
  value text not null,

  -- When this setting was last changed
  updated_at timestamptz default now()
);

alter table settings enable row level security;
create policy "Allow all on settings" on settings for all using (true) with check (true);

create table kung_fu_elements (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  -- minimum sash level required: red, yellow, next
  min_sash text not null default 'red' check (min_sash in ('red', 'yellow', 'next')),
  -- order for display purposes
  sort_order integer default 0,
  active boolean default true,
  created_at timestamptz default now()
);

alter table kung_fu_elements enable row level security;
create policy "Allow all on kung_fu_elements" on kung_fu_elements 
for all using (true) with check (true);

-- Seed with current elements
insert into kung_fu_elements (name, description, min_sash, sort_order) values
('Qi Gong', 'Stationary breathing practice — minimum 5 minutes daily', 'red', 1),
('Fa Jing', 'Explosive power practice combining single and triple strikes', 'red', 2),
('Footwork combinations', 'Base stance, single step and double step combinations', 'red', 3),
('Sup Luk Dun', '16 movements form — foundation of Lung Ying practice', 'red', 4),
('Sam Tong', 'Second level form', 'yellow', 5),
('Dan Bian', 'Third level form', 'next', 6),
('Si Men Da', 'Third level form', 'next', 7);